#!/usr/bin/env bash

accelerate launch run_distillation.py \
  --model_name_or_path "./distil-large-v3-init" \
  --teacher_model_name_or_path "openai/whisper-large-v3" \
  --train_dataset_name "litus-ai/common_voice_16_1_it_pseudo_labelled_whisper_large_v3+litus-ai/google_fleurs_it_pseudo_labelled_whisper_large_v3" \
  --train_split_name "train+train" \
  --train_dataset_config_name "it+it_it" \
  --text_column_name "sentence+transcription" \
  --eval_dataset_name "litus-ai/google_fleurs_it_pseudo_labelled_whisper_large_v3" \
  --eval_split_name "test" \
  --eval_dataset_config_name "it_it" \
  --eval_text_column_name "transcription" \
  --eval_steps 1000 \
  --save_steps 1000 \
  --warmup_steps 50 \
  --learning_rate 0.0001 \
  --lr_scheduler_type "constant_with_warmup" \
  --timestamp_probability 0.2 \
  --condition_on_prev_probability 0.2 \
  --language "it" \
  --task "transcribe" \
  --logging_steps 25 \
  --save_total_limit 1 \
  --max_steps 10000 \
  --wer_threshold 20 \
  --per_device_train_batch_size 16 \
  --per_device_eval_batch_size 16 \
  --dataloader_num_workers 8 \
  --preprocessing_num_workers 8 \
  --ddp_timeout 7200 \
  --dtype "bfloat16" \
  --attn_implementation "sdpa" \
  --output_dir "./" \
  --do_train \
  --do_eval \
  --gradient_checkpointing \
  --overwrite_output_dir \
  --predict_with_generate \
  --freeze_encoder \
  --freeze_embed_positions \
  --streaming False \
  --push_to_hub