accelerate launch run_pseudo_labelling.py \
  --model_name_or_path "openai/whisper-large-v3" \
  --dataset_name "facebook/voxpopuli" \
  --dataset_config_name "it" \
  --dataset_split_name "train+validation+test" \
  --text_column_name "raw_text" \
  --id_column_name "audio_id" \
  --output_dir "./voxpopuli_it_pseudo_labelled" \
  --per_device_eval_batch_size 16 \
  --dtype "bfloat16" \
  --attn_implementation "eager" \
  --logging_steps 500 \
  --max_label_length 256 \
  --concatenate_audio \
  --preprocessing_batch_size 500 \
  --preprocessing_num_workers 8 \
  --dataloader_num_workers 8 \
  --language "it" \
  --task "transcribe" \
  --return_timestamps \
  --streaming False \
  --generation_num_beams 1 \
  --push_to_hub
